#!/bin/bash
set -euo pipefail

# EulerSwap LP Agent — Anvil Fork Test
# Starts a mainnet fork, deploys pool + hook, outputs agent .env

# --- Config ---
RPC_URL="${RPC_URL:?Set RPC_URL to an Ethereum mainnet RPC endpoint}"
ANVIL_PORT="${ANVIL_PORT:-8545}"
ANVIL_RPC="http://localhost:$ANVIL_PORT"

# Anvil default account #0 (10000 ETH)
DEPLOYER="0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
DEPLOYER_KEY="0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"

# Tokens
USDC="0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"

# Known USDC whale (Circle reserve)
USDC_WHALE="0x55FE002aeff02F77364de339a1292923A15844B8"

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
CONTRACTS_DIR="$SCRIPT_DIR/../contracts"

# --- Cleanup on exit ---
cleanup() {
    if [ -n "${ANVIL_PID:-}" ]; then
        echo "Stopping Anvil (PID: $ANVIL_PID)..."
        kill "$ANVIL_PID" 2>/dev/null || true
    fi
}
trap cleanup EXIT

# --- Start Anvil ---
echo "Starting Anvil fork on port $ANVIL_PORT..."
anvil --fork-url "$RPC_URL" --port "$ANVIL_PORT" --silent &
ANVIL_PID=$!
sleep 3

# Verify Anvil is running
if ! cast block-number --rpc-url "$ANVIL_RPC" > /dev/null 2>&1; then
    echo "ERROR: Anvil failed to start"
    exit 1
fi
echo "Anvil running at $ANVIL_RPC (PID: $ANVIL_PID)"

# --- Fund deployer with USDC ---
echo "Funding deployer with USDC from whale..."
cast rpc anvil_impersonateAccount "$USDC_WHALE" --rpc-url "$ANVIL_RPC" > /dev/null
cast send "$USDC" "transfer(address,uint256)" "$DEPLOYER" 25000000000 \
    --from "$USDC_WHALE" --rpc-url "$ANVIL_RPC" --unlocked > /dev/null
cast rpc anvil_stopImpersonatingAccount "$USDC_WHALE" --rpc-url "$ANVIL_RPC" > /dev/null

USDC_BAL=$(cast call "$USDC" "balanceOf(address)(uint256)" "$DEPLOYER" --rpc-url "$ANVIL_RPC")
echo "Deployer USDC balance: $USDC_BAL (raw, 6 decimals)"

# --- Deploy pool + hook ---
echo ""
echo "Running Forge deploy script..."
cd "$CONTRACTS_DIR"
PRIVATE_KEY="$DEPLOYER_KEY" forge script script/DeployForkTest.s.sol:DeployForkTest \
    --fork-url "$ANVIL_RPC" --broadcast -vvv 2>&1 | tee /tmp/deploy-output.txt

# --- Extract addresses from output ---
echo ""
echo "============================================"
echo " Fork test environment ready!"
echo "============================================"
echo ""
echo "Anvil RPC: $ANVIL_RPC"
echo "Anvil PID: $ANVIL_PID"
echo ""

# Extract deployed addresses from forge output
POOL_ADDR=$(grep "POOL_ADDRESS=" /tmp/deploy-output.txt | tail -1 | sed 's/.*POOL_ADDRESS=//')
HOOK_ADDR=$(grep "HOOK_ADDRESS=" /tmp/deploy-output.txt | tail -1 | sed 's/.*HOOK_ADDRESS=//')
EVC_ADDR=$(grep "EVC_ADDRESS=" /tmp/deploy-output.txt | tail -1 | sed 's/.*EVC_ADDRESS=//')
EULER_ACCT=$(grep "EULER_ACCOUNT=" /tmp/deploy-output.txt | tail -1 | sed 's/.*EULER_ACCOUNT=//')

if [ -n "$POOL_ADDR" ]; then
    # Write .env file
    cat > "$SCRIPT_DIR/.env.fork" << EOF
# Generated by fork-test.sh — $(date)
RPC_URL=$ANVIL_RPC
PRIVATE_KEY=$DEPLOYER_KEY
POOL_ADDRESS=$POOL_ADDR
HOOK_ADDRESS=$HOOK_ADDR
EVC_ADDRESS=$EVC_ADDR
EULER_ACCOUNT=$EULER_ACCT
ANTHROPIC_API_KEY=\${ANTHROPIC_API_KEY}
POLL_INTERVAL=10
CLAUDE_REVIEW_INTERVAL=300
DAILY_GAS_BUDGET=1000000000000000000
EOF
    echo "Written: agent/.env.fork"
    echo ""
    echo "To run the agent:"
    echo "  cp agent/.env.fork agent/.env"
    echo "  # Set ANTHROPIC_API_KEY in agent/.env"
    echo "  cd agent && npm start"
else
    echo "WARNING: Could not extract addresses from deploy output."
    echo "Check /tmp/deploy-output.txt for details."
fi

echo ""
echo "Press Ctrl+C to stop Anvil."
echo ""

# Keep script running so Anvil stays alive
trap - EXIT  # Disable cleanup trap — user will Ctrl+C
wait "$ANVIL_PID"
